#!/bin/bash
#
# Monitor the wlan0 and reset up to 5 times then restart the RPi

while true; do
  if ifconfig wlan0 | grep -q "inet addr:"; then
    count=0
    sleep 10
  else
    let "count++"
    echo "Network connection down."
    if [ "count" == "5" ] ; then
      shutdown -r now
      sleep 10
    else
      ifdown --force wlan0
      sleep 10
      ifup --force wlan0
      sleep 10
    fi
  fi
done
	
